= Problemstellung <problemstellung>

Die Klassifikation von Landnutzung und Landbedeckung (Land Use and Land Cover, LULC) stellt eine zentrale Säule der modernen Erdbeobachtung dar und ist essenziell für die Überwachung von Umweltveränderungen, die Stadtplanung sowie das Katastrophenmanagement @helber2019eurosat. Durch das Copernicus-Programm der Europäischen Union stehen mit den Sentinel-2-Satelliten hochauflösende, multispektrale Bilddaten offen zur Verfügung, die jedoch aufgrund ihrer enormen Menge und Komplexität eine automatisierte Auswertung erfordern. Die Herausforderung bei der Klassifikation dieser Satellitendaten liegt insbesondere in der Extraktion signifikanter Merkmale aus oft repetitiven Mustern und feinen Texturunterschieden, wie sie beispielsweise bei der Unterscheidung verschiedener landwirtschaftlicher Nutzflächen oder urbaner Strukturen auftreten @helber2019eurosat.

Im Rahmen dieser Projektarbeit soll die Leistungsfähigkeit moderner Deep-Learning-Verfahren zur Lösung dieser Klassifikationsaufgabe am Beispiel des EuroSAT-Datensatzes untersucht werden. Die Aufgabenstellung umfasst dabei gemäß den Projektanforderungen die Umsetzung und den kritischen Vergleich zweier unterschiedlicher Modellphilosophien:

+ *Modell 1 (From Scratch):* Die Entwicklung einer Convolutional Neural Network (CNN) Architektur, bei der sämtliche Designentscheidungen von der Layer-Wahl bis zu den Hyperparametern eigenständig begründet werden müssen. Hierbei wird sich an etablierten Architekturprinzipien wie denen von VGGNet @simonyan2014vgg oder ResNet @he2015resnet orientiert.
+ *Modell 2 (Transfer Learning):* Die Implementierung eines Transfer-Learning-Ansatzes, der auf vortrainierten Modellen basiert, um die Vorteile bereits erlernter Feature-Repräsentationen für die spezifischen Anforderungen der Satellitenbildanalyse zu nutzen @shahriar2025lightweight.

Darüber hinaus erfordert die Problemstellung die Bearbeitung zweier unterschiedlicher Klassifikationsszenarien auf demselben Datensatz: eine *Mehrklassenklassifikation* zur Unterscheidung der zehn im EuroSAT-Datensatz enthaltenen Landnutzungskategorien sowie eine *binäre Klassifikation*, um die Generalisierungsfähigkeit der Modelle unter variierenden Anforderungen zu prüfen. Die zentrale Schwierigkeit besteht dabei darin, Architekturen zu finden, die robust genug agieren, um dem bei kleineren Bildgrößen (64x64 Pixel) häufig auftretenden Problem des Overfittings zu begegnen.

Das Ziel der Arbeit ist es, die spezifischen Vor- und Nachteile der beiden Modellansätze hinsichtlich Genauigkeit, Konvergenzverhalten und Ressourceneffizienz systematisch herauszuarbeiten. Durch den direkten Vergleich soll bewertet werden, inwiefern vortrainierte Gewichte den Trainingsprozess beschleunigen und die Klassifikationsleistung bei Satellitendaten im Vergleich zu spezialisierten Eigenentwicklungen steigern können.