= Convolutional Neural Network mit Transfer Learning

Durch die Analyse des Datensatzes sowie den Experimenten mit dem Netz von Scratch war klar, dass der Datensatz ein kleines Netzwerk braucht und dass Overfitting das größte Problem sein würde. Daher war die Auswahl von Vortrainierten Netzen von Anfang an auf kleine Netze (meist für Edge Use Cases vorgesehen) beschränkt.

== State of the Art Analyse 

Eine aktuelle Vergleichsstudie analysiert verschiedene Lightweight-Architekturen hinsichtlich ihrer Eignung für ressourcenbeschränkte Anwendungen. In dieser Arbeit werden unter anderem MobileNetV3Small, EfficientNetV2, ResNet18, SqueezeNet und ShuffleNetV2 auf mehreren Bildklassifikationsdatensätzen evaluiert. Die Modelle werden dabei anhand zentraler Metriken wie Klassifikationsgenauigkeit, Inferenzzeit, FLOPs und Modellgröße verglichen. Die Ergebnisse zeigen, dass EfficientNetV2 zwar die höchste Genauigkeit erzielt, jedoch mit einem höheren Rechenaufwand verbunden ist, während MobileNetV3Small den besten Kompromiss zwischen Genauigkeit und Effizienz bietet. Zudem wird hervorgehoben, dass Transfer Learning die Leistungsfähigkeit aller Modelle signifikant verbessert, insbesondere bei komplexeren Datensätzen. @shahriar2025lightweight

== Wahl des Modells

Aufgrund der Ergebnisse der Vergleichsstudie haben wir uns für MobileNetV3Small entschieden. 

Die Architektur von MobileNetV3Small basiert auf einer Weiterentwicklung der MobileNetV2-Struktur und kombiniert mehrere effizienzorientierte Designprinzipien. Zentrale Bausteine sind sogenannte Inverted Residual Bottleneck Blocks, die Depthwise-Separable-Convolutions zur Reduktion des Rechenaufwands nutzen. Diese werden durch Squeeze-and-Excitation-Module ergänzt, welche eine adaptive Gewichtung der Feature-Kanäle ermöglichen und somit die Repräsentationsfähigkeit verbessern. Zusätzlich führt MobileNetV3 spezialisierte Aktivierungsfunktionen wie h-swish ein, die eine bessere Balance zwischen numerischer Effizienz und Modellgenauigkeit bieten. Die konkrete Architektur wurde mithilfe hardwarebewusster Neural Architecture Search sowie des NetAdapt-Algorithmus optimiert, wodurch ein Modell entsteht, das gezielt auf geringe Latenz und hohe Effizienz ausgelegt ist. @howard2019mobilenetv3

Im Kontext der Klassifikation von Satellitenbildern, wie sie im EuroSAT-Datensatz vorliegen, erweist sich die Architektur von MobileNetV3Small als besonders vorteilhaft. Satellitenbilder zeichnen sich häufig durch großflächige, repetitive Muster und feine Texturunterschiede aus, etwa bei der Unterscheidung von landwirtschaftlichen Flächen, urbanen Gebieten oder Gewässern. Die in MobileNetV3Small eingesetzten Depthwise-Separable-Convolutions ermöglichen eine effiziente Extraktion solcher lokal relevanten Merkmale, ohne dabei unnötige Redundanzen zu erzeugen. Gleichzeitig sorgen Squeeze-and-Excitation-Mechanismen für eine adaptive Gewichtung der Feature-Kanäle, wodurch besonders informative spektrale und strukturelle Merkmale hervorgehoben werden können. Dies ist insbesondere bei Satellitendaten relevant, da hier unterschiedliche Oberflächenstrukturen oft nur durch subtile Unterschiede im Frequenz- und Intensitätsbereich voneinander getrennt sind. In Kombination mit vortrainierten Gewichten führt dies dazu, dass MobileNetV3Small die charakteristischen Muster des Datensatzes effizient erfassen und generalisieren kann, wodurch eine hohe Klassifikationsleistung bei gleichzeitig geringer Modellkomplexität erreicht wird. @howard2019mobilenetv3 @helber2019eurosat