= Convolutional Neural Network mit Transfer Learning

Auf Grundlage der Datensatzanalyse und der Experimente mit einem Netzwerk von Grund auf wurde deutlich, dass ein kleines Netzwerk erforderlich ist und dass Overfitting das Hauptproblem darstellt. Daher beschränkte sich die Auswahl vortrainierter Netzwerke von Anfang an auf kleine Modelle, die typischerweise für ressourcenbeschränkte Anwendungen vorgesehen sind.

== State of the Art Analyse

Eine aktuelle Vergleichsstudie analysiert verschiedene Lightweight-Architekturen hinsichtlich ihrer Eignung für ressourcenbeschränkte Anwendungen. Darin werden unter anderem MobileNetV3Small, EfficientNetV2, ResNet18, SqueezeNet und ShuffleNetV2 auf mehreren Bildklassifikationsdatensätzen evaluiert. Die Modelle werden anhand zentraler Metriken wie Klassifikationsgenauigkeit, Inferenzzeit, FLOPs und Modellgröße verglichen. Die Ergebnisse zeigen, dass EfficientNetV2 zwar die höchste Genauigkeit erreicht, jedoch mit höherem Rechenaufwand verbunden ist, während MobileNetV3Small den besten Kompromiss zwischen Genauigkeit und Effizienz bietet. Die Analysen belegen zudem, dass Transfer Learning die Leistungsfähigkeit aller Modelle signifikant verbessert, insbesondere bei komplexeren Datensätzen. @shahriar2025lightweight

== Wahl des Modells

Basierend auf den Ergebnissen der Vergleichsstudie wurde MobileNetV3Small als Architektur ausgewählt.

Die Architektur von MobileNetV3Small basiert auf einer Weiterentwicklung der MobileNetV2-Struktur und integriert mehrere effizienzorientierte Designprinzipien. Zentrale Bausteine sind sogenannte Inverted Residual Bottleneck Blocks, welche Depthwise-Separable-Convolutions zur Reduktion des Rechenaufwands nutzen. Diese werden durch Squeeze-and-Excitation-Module ergänzt, die eine adaptive Gewichtung der Feature-Kanäle ermöglichen und somit die Repräsentationsfähigkeit verbessern. Zudem führt MobileNetV3 spezialisierte Aktivierungsfunktionen wie h-swish ein, die einen besseren Kompromiss zwischen numerischer Effizienz und Modellgenauigkeit bieten. Die konkrete Architektur wurde durch hardwarebewusste Neural Architecture Search und den NetAdapt-Algorithmus optimiert, was zu einem Modell führt, das gezielt auf geringe Latenz und hohe Effizienz ausgelegt ist. @howard2019mobilenetv3

Bei der Klassifikation von Satellitenbildern, wie sie im EuroSAT-Datensatz vorliegen, erweist sich MobileNetV3Small als besonders geeignet. Satellitenbilder zeichnen sich durch großflächige, repetitive Muster und feine Texturunterschiede aus, etwa bei der Unterscheidung von landwirtschaftlichen Flächen, urbanen Gebieten oder Gewässern. Die in MobileNetV3Small eingesetzten Depthwise-Separable-Convolutions ermöglichen eine effiziente Extraktion lokal relevanter Merkmale ohne unnötige Redundanzen. Gleichzeitig sorgen Squeeze-and-Excitation-Mechanismen für eine adaptive Gewichtung der Feature-Kanäle, wodurch besonders informative spektrale und strukturelle Merkmale hervorgehoben werden. Dies ist bei Satellitendaten relevant, da unterschiedliche Oberflächenstrukturen oft nur durch subtile Unterschiede im Frequenz- und Intensitätsbereich unterschieden werden. In Kombination mit vortrainierten Gewichten kann MobileNetV3Small die charakteristischen Muster des Datensatzes effizient erfassen und generalisieren, was zu einer hohen Klassifikationsleistung bei geringer Modellkomplexität führt. @howard2019mobilenetv3 @helber2019eurosat
